#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

sys_set_attribute -gui on -msg {/home/anonymous/code/cva6/corev_apu/fpga/lattice/promote.xml}
msg_load {/home/anonymous/code/cva6/corev_apu/fpga/lattice/promote.xml}
des_set_project_udb -in {cva6_1_impl_1_syn.udb} -out {cva6_1_impl_1_map.udb} -milestone map -pm ap6a00b
des_set_reference_udb -clean
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false infer_gsr false  ignore_constraint_errors false}
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
